In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
#dataset=pd.read_excel(r'DataFinal17-20.xlsx',sheet_name='2020')
df=pd.read_excel(r'DataFinal17-20.xlsx',sheet_name='2020')
df1=df.iloc[:,2:22]
df1=df1.drop(['Total','Crime Rate','Sex Ratio','Literacy','Density'], axis=1)
df1.head()

Homicide/Murder  Causing death by negligence  Hurt  Assault on woman  \
0              254                          620  1826               543   
1              114                          116  1345               245   
2              201                          354  2133               461   
3              139                          386  1869               335   
4              206                          308  1233               248   

   Kidnapping and abduction  Human trafficking   Rape  \
0                       369                   0    92   
1                        76                   0    28   
2                       190                   0    97   
3                       242                   0    80   
4                        91                   0    50   

   Offence against public tranquility  Offences against property  \
0                                 905                       3104   
1                                 111                        946   
2                                 144                       2198   
3                                 428                       3821   
4                                 508                       1002   

   Offences relating to documents and property marks  Miscellaneous  Others  \
0                                                220          30535     221   
1                                                 86           4244     213   
2                                                250           3921     164   
3                                                265           4292     411   
4                                                104           1858     111   

   Population   Latitude  Longitude  
0     4543159  19.094829  74.747979  
1     1813906  20.700216  77.008168  
2     2888445  20.931982  77.752304  
3     3701282  19.876165  75.343314  
4     2585049  18.990088  75.753132

In [3]:
#data=pd.read_excel(r'DataFinal17-20.xlsx')

In [4]:
#dataset.head()

In [5]:
#for col in data:
#    print (type(data[col][1]))
from sklearn import preprocessing
from sklearn import utils

# Extracting Independent and dependent Variable 

In [6]:

x= df1.iloc[:, [0,1,2,3,4,5,6,7,8,9,10,11,12]].values  
y= df1.iloc[:, [13]].values  
#a1 = preprocessing.LabelEncoder()
#y_trans = a1.fit_transform(y)

In [7]:
x

array([[     254,      620,     1826,      543,      369,        0,
              92,      905,     3104,      220,    30535,      221,
         4543159],
       [     114,      116,     1345,      245,       76,        0,
              28,      111,      946,       86,     4244,      213,
         1813906],
       [     201,      354,     2133,      461,      190,        0,
              97,      144,     2198,      250,     3921,      164,
         2888445],
       [     139,      386,     1869,      335,      242,        0,
              80,      428,     3821,      265,     4292,      411,
         3701282],
       [     206,      308,     1233,      248,       91,        0,
              50,      508,     1002,      104,     1858,      111,
         2585049],
       [      41,      141,      486,       88,       71,        0,
              16,       43,      676,       60,     1051,       54,
         1200334],
       [     122,      293,     2099,      313,      110,        0,
  

In [8]:
y

array([[19.0948287],
       [20.7002159],
       [20.9319821],
       [19.8761653],
       [18.990088 ],
       [21.177658 ],
       [20.5292147],
       [19.9615398],
       [20.9042201],
       [20.184871 ],
       [21.4549477],
       [19.7173703],
       [21.0076578],
       [19.8346659],
       [16.7049873],
       [18.4087934],
       [19.0759837],
       [19.1538231],
       [21.1458004],
       [19.1382514],
       [21.7468548],
       [19.9974533],
       [18.185332 ],
       [19.2608384],
       [18.5204303],
       [18.2376278],
       [16.990215 ],
       [16.8523973],
       [17.6804639],
       [16.3492193],
       [17.6599188],
       [19.2183307],
       [20.745319 ],
       [20.1119123],
       [20.3899385]])

# Splitting the dataset into training and test set  

In [9]:
from sklearn.model_selection import train_test_split  
x_train, x_test, y_train, y_test= train_test_split(x, y, test_size= 0.25, random_state=0) 

In [10]:
x_train

array([[     207,      269,     1344,      250,      228,        2,
              39,      340,     1678,      197,     1756,      293,
         2822143],
       [      47,      191,      334,       77,       73,        0,
              20,      165,      533,      141,      474,      105,
         2634200],
       [     140,      310,     1431,      187,      128,        1,
              44,       85,      923,       56,     4117,      138,
         2772348],
       [      86,      170,     1394,      197,      113,        0,
              25,       44,      741,       88,     1980,       24,
         1300774],
       [      39,      106,      250,       53,       43,        0,
              11,      109,      361,      113,      388,       18,
         1615069],
       [     246,      461,     2437,      449,      276,        8,
              96,      786,     3046,      289,     2906,     3744,
         4317756],
       [      84,      352,      433,       80,       98,        1,
  

In [11]:
x_test

array([[      18,       50,      241,       53,       18,        0,
               6,       43,      178,       48,      330,       14,
          849651],
       [     240,      917,     1720,      384,      473,        1,
              65,      637,     2528,      529,    18068,      347,
         6107187],
       [     521,      349,     4171,     1553,     1180,       58,
             331,      392,    17530,     3425,    19788,     9146,
        12442373],
       [     145,      359,     1017,      275,      192,        2,
              49,      481,     1557,      183,     2986,      162,
         3003741],
       [      92,      253,      847,      123,       87,        0,
              21,      247,      685,       80,     1126,       61,
         1657576],
       [     104,      244,     1077,      138,      111,        3,
              26,      303,      964,       94,     2000,       82,
         2454196],
       [      50,      131,      311,       57,       40,        0,
  

In [12]:
y_train

array([[16.8523973],
       [18.2376278],
       [20.3899385],
       [20.745319 ],
       [16.990215 ],
       [17.6599188],
       [20.9042201],
       [19.8346659],
       [21.177658 ],
       [19.1538231],
       [16.7049873],
       [19.2183307],
       [18.5204303],
       [20.7002159],
       [21.0076578],
       [20.5292147],
       [19.2608384],
       [18.990088 ],
       [21.1458004],
       [19.9974533],
       [19.1382514],
       [20.184871 ],
       [19.9615398],
       [20.1119123],
       [19.8761653],
       [19.0948287]])

In [13]:
y_test

array([[16.3492193],
       [21.7468548],
       [19.0759837],
       [17.6804639],
       [18.185332 ],
       [18.4087934],
       [21.4549477],
       [20.9319821],
       [19.7173703]])

# Fitting K-NN classifier to the training set  

In [14]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=10)
knn.fit(x_train,y_train) 

c:\users\welcome\appdata\local\programs\python\python39\lib\site-packages\sklearn\neighbors\_classification.py:179: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


ValueError: Unknown label type: 'continuous'